nit: removed extra s
forgecommunitywiki/Documentation pull request #34
Opened 2021-05-01 15:53 UTC by scrouthtv

removed extra s

2021-05-01 15:54 UTC, ravenbuilder934 submitted a review, later dismissed

2021-05-01 19:20 UTC, AterAnimAvis approved these changes

2021-05-01 19:47 UTC, AterAnimAvis requested changes
Thank you for the contribution.

Could your change your branch target to forgecommunitywiki:1.15.x-omnibus?

This change applies to both 1.15 and 1.16.

2021-05-02 07:15 UTC, scrouthtv commented
Nope that doesn't work. But I can create a new one

2021-05-02 07:15 UTC, closed without merging